<h3 class="text-center" style="padding-top: 10px; font-family: 'OleoScript-Regular';">Privacy policy</h3>
<p style="font-size:15px;text-align: left;font-family: inherit; padding: 17px;
    padding-top: 16px;">Website Privacy Policy
This web site is owned and operated by the Easy Imex Ltd and will be referred to as "We", "our" and "us" in this Internet Privacy Policy. By using this site, you agree to the Internet Privacy Policy of this web site ("the web site"), which is set out on this web site page. The Internet Privacy Policy relates to the collection and use of personal information you may supply to us through your conduct on the web site. 
We reserve the right, at our discretion, to modify or remove portions of this Internet Privacy Policy at any time. This Internet Privacy Policy is in addition to any other terms and conditions applicable to the web site. We do not make any representations about third party web sites that may be linked to the web site. 
We recognise the importance of protecting the privacy of information collected about visitors to our web site, in particular information that is capable of identifying an individual ("personal information"). This Internet Privacy Policy governs the manner in which your personal information, obtained through the web site, will be dealt with. This Internet Privacy Policy should be reviewed periodically so that you are updated on any changes. We welcome your comments and feedback. 
<h3 class="text-center" style="font-family: 'OleoScript-Regular';">Personal Informtion</h3>
<p style="font-size:15px;text-align: left;font-family: inherit; padding: 17px;
    padding-top: 16px;">Personal information about visitors to our site is collected only when knowingly and voluntarily submitted. For example, we may need to collect such information to provide you with further services or to answer or forward any requests or enquiries. It is our intention that this policy will protect your personal information from being dealt with in any way that is inconsistent with applicable privacy laws in Australia, UK, Ireland, South Africa, NZ or USA.  
<h3 class="text-center" style="font-family: 'OleoScript-Regular';">Use of information</h3>
<p style="font-size:15px;text-align: left;font-family: inherit; padding: 17px;
    padding-top: 16px;">Personal information that visitors submit to our site is used only for the purpose for which it is submitted or for such other secondary purposes that are related to the primary purpose, unless we disclose other uses in this Internet Privacy Policy or at the time of collection. Copies of correspondence sent from the web site, that may contain personal information, are stored as archives for record-keeping and back-up purposes only.  
</p><br>